version: '3.8'

services:
  screenshot-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: screenshot-service:latest
    container_name: screenshot-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MAX_CONCURRENT_JOBS=5
      - CHROME_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - DATA_DIR=/app/data
    volumes:
      - screenshot-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 可选：添加底图配置工具UI服务
  basemap-config:
    build:
      context: ./cesium-basemap-config
      dockerfile: Dockerfile
    image: cesium-basemap-config:latest
    container_name: cesium-basemap-config
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - screenshot-service
    environment:
      - VITE_SERVER_URL=http://screenshot-service:3000

volumes:
  screenshot-data:
    driver: local 